In [174]:
#task 2: pick the last one to win
#same as before but pick the highest nr as winner

import numpy as np

def main():
    #convert input string to dictionary of np-matrixes
    idxdict = dict(zip([str(i) for i in inp[0].split(",")], list(range(len(inp[0].split(","))))))
    tables = {}
    mtxin = ""
    x = iter(list(range(100)))
    for row in inp1:
        if row != "":
            converted = ' '.join([str(idxdict[i]) for i in row.split(' ') if i])
            mtxin+=f"{converted};"
        else:
            tables[next(x)] = np.matrix(mtxin[:-1])
            mtxin = ""

    
    #check when a table wins
    #write results to windict
    windict = {}
    x = iter(list(range(100)))
    for idx in tables:
        #print(tab)
        #print(min([i for i in np.max(tables[idx], axis=0).flat]))
        windict[next(x)] = min([i for i in np.max(tables[idx], axis=0).flat] + [i for i in np.max(tables[idx], axis=1).flat])
    
    #pick the winning table
    hm = 0
    idxwin = None
    for i in windict:
        if windict[i] > hm:
            idxwin = i
            hm = windict[i]
   
    ###calculate sum of missing numbers
    #convert indices back to actual numbers
    valdict = {value: key for key, value in idxdict.items()}
    return sum(int(i) for i in [valdict[i] for i in tables[idxwin].flat if valdict[i] not in inp[0].split(",")[:windict[idxwin]+1]])*[int(i) for i in inp[0].split(",")][:windict[idxwin]+1][-1]
    
main()

7075

In [ ]:
inp[0].split(",") == list(dict.fromkeys(inp[0].split(",")))

In [101]:
len(inp[0].split(",")[:23])

23

In [ ]:
idxdict = dict(zip([str(i) for i in inp[0].split(",")], list(range(len(inp[0].split(","))))))
idxdict

In [46]:
vocab_tage = {value: key for key, value in tag_vocab.items()}

['a']

In [134]:
inp1

'4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1\n\n22 13 17 11  0\n 8  2 23  4 24\n21  9 14 16  7\n 6 10  3 18  5\n 1 12 20 15 19\n\n 3 15  0  2 22\n 9 18 13 17  5\n19  8  7 25 23\n20 11 10 24  4\n14 21 16 12  6\n\n14 21 17 24  4\n10 16 15  9 19\n18  8 23 26 20\n22 11 13  6  5\n 2  0 12  3  7'

In [173]:
import numpy as np

def main():
    #convert input string to dictionary of np-matrixes
    idxdict = dict(zip([str(i) for i in inp[0].split(",")], list(range(len(inp[0].split(","))))))
    tables = {}
    mtxin = ""
    x = iter(list(range(100)))
    for row in inp1:
        if row != "":
            converted = ' '.join([str(idxdict[i]) for i in row.split(' ') if i])
            mtxin+=f"{converted};"
        else:
            tables[next(x)] = np.matrix(mtxin[:-1])
            mtxin = ""

    
    #check when a table wins
    #write results to windict
    windict = {}
    x = iter(list(range(100)))
    for idx in tables:
        #print(tab)
        #print(min([i for i in np.max(tables[idx], axis=0).flat]))
        windict[next(x)] = min([i for i in np.max(tables[idx], axis=0).flat] + [i for i in np.max(tables[idx], axis=1).flat])
    
    #pick the winning table
    hm = 100
    idxwin = None
    for i in windict:
        if windict[i] < hm:
            idxwin = i
            hm = windict[i]
   
    ###calculate sum of missing numbers
    #convert indices back to actual numbers
    valdict = {value: key for key, value in idxdict.items()}
    return sum(int(i) for i in [valdict[i] for i in tables[idxwin].flat if valdict[i] not in inp[0].split(",")[:windict[idxwin]+1]])*[int(i) for i in inp[0].split(",")][:windict[idxwin]+1][-1]
    
main()

16674

In [151]:
windict

{0: 13, 1: 14}

In [156]:
inp="""7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
""".split("\n")
inp1=inp[2:]

In [140]:
inp1

['22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [128]:
tables[idxwin]

matrix([[15, 18, 22, 19, 12],
        [45, 83, 99, 85,  9],
        [76, 56, 31, 53,  2],
        [47, 57, 38, 64, 21],
        [70, 33, 88, 95, 28]])

In [ ]:
tables

In [108]:
inp[0].split(",")[:22]

['42',
 '44',
 '71',
 '26',
 '70',
 '92',
 '77',
 '45',
 '6',
 '18',
 '79',
 '54',
 '31',
 '34',
 '64',
 '32',
 '16',
 '55',
 '81',
 '11',
 '90',
 '10']

In [68]:
a = np.arange(12).reshape(4,3)
s1 = np.max(a, axis=0)
s2 = np.max(a, axis=0)
list(s1)+list(s2)

[9, 10, 11, 9, 10, 11]

In [63]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
import numpy as np

np.matrix('48 69 68 49 13;25 14 30 74 89;16 38 19 24 29;56 97 50 65 79;57 52  5 27 76')

matrix([[48, 69, 68, 49, 13],
        [25, 14, 30, 74, 89],
        [16, 38, 19, 24, 29],
        [56, 97, 50, 65, 79],
        [57, 52,  5, 27, 76]])

In [135]:
inp1

'4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1\n\n22 13 17 11  0\n 8  2 23  4 24\n21  9 14 16  7\n 6 10  3 18  5\n 1 12 20 15 19\n\n 3 15  0  2 22\n 9 18 13 17  5\n19  8  7 25 23\n20 11 10 24  4\n14 21 16 12  6\n\n14 21 17 24  4\n10 16 15  9 19\n18  8 23 26 20\n22 11 13  6  5\n 2  0 12  3  7'

In [172]:
inp1=inp[2:]

In [171]:
with open("in.txt", "r") as f:
    inp = f.read().split("\n")